name: VyntoCore
version: 1.0.0
main: me.vynto.core.VyntoCore
authors: ["Harrison", "Josh"]
api-version: 1.16

commands:
  hat:
    usage: /hat
    description: Wear the item you're currently holding as a hat.
    permission: vynto.core.hat
  skull:
    usage: /skull
    description: Give yourself a specific player skull.
    permission: vynto.core.skull

permissions:
  vynto.core.hat:
    description: Gain access to the /hat command
    default: op
  vynto.core.hat.others:
    description: Use the /hat command on others
    default: op
  vynto.core.skull:
    description: Gain access to the /skull command
    default: op