name: VyntoCore
version: 1.0.0
main: me.vynto.core.VyntoCore
authors: ["Harrison", "Josh"]
api-version: 1.16

commands:
  hat:
    usage: /hat
    description: Wear the item you're currently holding as a hat.
    permission: vynto.core.hat
  skull:
    usage: /skull
    description: Give yourself a specific player skull.
    permission: vynto.core.skull
  fly:
    usage: /fly
    description: Toggle your flying
    permission: vynto.core.fly
  heal:
    usage: /heal
    description: Heal a player.
    permission: vynto.core.heal
  feed:
    usage: /feed
    description: Feed a player.
    permission: vynto.core.feed


permissions:
  vynto.core.hat:
    description: Gain access to the /hat command
    default: op
  vynto.core.hat.others:
    description: Use the /hat command on others
    default: op
  vynto.core.skull:
    description: Gain access to the /skull command
    default: op
  vynto.core.fly:
    description: Gain access to the /fly command
    default: op
  vynto.core.fly.others:
    description: Use the /fly command on others
    default: op
  vynto.core.heal:
    description: Gain access to the heal command
    default: op
  vynto.core.heal.other:
    description: Use the /heal command on others
    default: op
  vynto.core.feed:
    description: Gain access to the feed command
    default: op
  vynto.core.feed.others:
    description: Use the /feed command on others
    default: op