name: VyntoCore
version: 1.0.0
main: me.vynto.core.VyntoCore
authors: ["Harrison", "Josh"]
api-version: 1.16

commands:
  hat:
    usage: /hat
    description: Wear the item you're currently holding as a hat.
    permission: vynto.core.hat
  skull:
    usage: /skull
    description: Give yourself a specific player skull.
    permission: vynto.core.skull
  fly:
    usage: /fly
    description: Toggle your flying
    permission: vynto.core.fly
  heal:
    usage: /heal
    description: Heal a player.
    permission: vynto.core.heal
  feed:
    usage: /feed
    description: Feed a player.
    permission: vynto.core.feed
  workbench:
    usage: /workbench
    aliases: ["craftingtable"]
    description: Open a workbench on a player.
    permission: vynto.core.workbench
  book:
    usage: /book
    description: Open the book editor settings.
    permission: vynto.core.book
  repair:
    usage: /repair
    description: Repair a player's damaged tool.
    permission: vynto.core.repair
  anvil:
    usage: /anvil
    description: Open an anvil on a player.
    permission: vynto.core.anvil
  gamemode:
    usage: /gamemode [gamemode]
    description: Change your gamemode.
    permission: vynto.core.gamemode
    aliases: ["gm", "gmc", "gma", "gmsp", "gms"]
  msg:
    usage: /msg <player> <msg ...>
    description: Message another player.
    permission: vynto.core.message
    aliases: ["pm"]
  r:
    usage: /r <msg ...>
    description: Reply to a player.
    permission: vynto.core.reply
    aliases: ["reply"]
  broadcast:
    usage: /broadcast <msg ...>
    description: Broadcast a message to the entire server.
    permission: vynto.core.broadcast
    aliases: ["bc"]
  online:
    usage: /online
    description: Check how many players are online or if a specific player is online.
    permission: vynto.core.online
  tp:
    usage: /tp <player>
    description: Teleport to another player.
    permission: vynto.core.teleport.players
    aliases: ["teleport"]
  tppos:
    usage: /tppos <x> <y> <z>
    description: Teleport to a location.
    permission: vynto.core.teleport.position
  party:
    usage: /party
    description: Interact with parties.
    permission: vynto.core.party
    aliases: ["p", "pc"]
  enderchest:
    usage: /enderchest
    description: Open your enderchest or the enderchest of others.
    permission: vynto.core.enderchest
    aliases: [ "ec" ]
  invsee:
    usage: /invsee <player>
    description: Open your inventory of others.
    permission: vynto.core.invsee
  border:
    usage: /border <radius> <player|all>
    description: Create a world border from your location using the specified radius.
    permission: vynto.core.border
  playertag:
    usage: /playertag <colour>
    description: Set your player tag colour.
    permission: vynto.core.playertag
  nickname:
    usage: /nickname <player> <nickname>
    description: Set a player's nickname.
    permission: vynto.core.nickname
    aliases: [ "nick" ]

permissions:
  vynto.core.hat:
    description: Gain access to the /hat command
    default: op
  vynto.core.hat.others:
    description: Use the /hat command on others
    default: op
  vynto.core.skull:
    description: Gain access to the /skull command
    default: op
  vynto.core.fly:
    description: Gain access to the /fly command
    default: op
  vynto.core.fly.others:
    description: Use the /fly command on others
    default: op
  vynto.core.heal:
    description: Gain access to the heal command
    default: op
  vynto.core.heal.other:
    description: Use the /heal command on others
    default: op
  vynto.core.feed:
    description: Gain access to the feed command
    default: op
  vynto.core.feed.others:
    description: Use the /feed command on others
    default: op
  vynto.core.workbench:
    description: Gain access to the workbench command
    default: op
  vynto.core.book.*:
    description: Use all /book commands
    default: op
  vynto.core.book.title:
    description: Use the /book title command
    default: op
  vynto.core.book.author:
    description: Use the /book author command
    default: op
  vynto.core.book.copy:
    description: Use the /book copy command
    default: op
  vynto.core.book.copy.share:
    description: Use the /book copy command to share a book
    default: op
  vynto.core.repair:
    description: Gain access to the /repair command
    default: op
  vynto.core.repair.others:
    description: Use the /repair command on others
    default: op
  vynto.core.anvil:
    description: Gain access to the /anvil command
    default: op
  vynto.core.anvil.others:
    description: Use the /anvil command on others
    default: op
  vynto.core.gamemode.creative:
    description: Set your gamemode to creative
    default: op
  vynto.core.gamemode.adventure:
    description: Set your gamemode to adventure
    default: op
  vynto.core.gamemode.survival:
    description: Set your gamemode to survival
    default: op
  vynto.core.gamemode.spectator:
    description: Set your gamemode to spectator
    default: op
  vynto.core.gamemode.others:
    description: Use the /gamemode command on others
    default: op
  vynto.core.message:
    description: Use the /msg command
    default: op
  vynto.core.message.console:
    description: Use the /msg command with the console
    default: op
  vynto.core.reply:
    description: Use the /r command
    default: op
  vynto.core.broadcast:
    description: Use the /bc command
    default: op
  vynto.core.online:
    description: Use the /online command
    default: op
  vynto.core.online.others:
    description: Use the /online command on others
    default: op
  vynto.core.teleport.players:
    description: Use the /tp command
    default: op
  vynto.core.teleport.players.others:
    description: Use the /tp command on others
    default: op
  vynto.core.teleport.position:
    description: Use the /tppos command
    default: op
  vynto.core.teleport.position.others:
    description: Use the /tppos command on others
    default: op
  vynto.core.party:
    description: Use the /party commands
    default: op
  vynto.core.party.create:
    description: Use the /party create command
    default: op
  vynto.core.enderchest:
    description: Use the /enderchest command
    default: op
  vynto.core.enderchest.others:
    description: Use the /enderchest command on others to view or modify their enderchest
    default: op
  vynto.core.inventory:
    description: Use the /invsee command to view or modify player inventories
    default: op
  vynto.core.border:
    description: Use the /border command
    default: op
  vynto.core.playertag:
    description: Use the /playertag command
    default: op
  vynto.core.nickname:
    description: Use the /nickname command
    default: op
  vynto.core.colour:
    description: Use colour in chat
    default: op